export const MEMORY_READ_MESSAGES: Record<string, Record<string, string>> = {
  'memory_read.id': { en: 'Record ID', tr: 'Kayıt kimliği' },
  'memory_read.revision': { en: 'Selection revision', tr: 'Seçim revizyonu' },
  'memory_read.scope': { en: 'Memory scope', tr: 'Bellek kapsamı' },
  'memory_read.context_heading': { en: 'Relevant project memory', tr: 'İlgili proje belleği' },
  'memory_read.unavailable': { en: 'Unavailable', tr: 'Kullanılamıyor' },
  'bot.memory.context.heading': { en: 'Project memory context', tr: 'Proje bellek bağlamı' },
  'bot.memory.context.guidance': {
    en: 'Use the complete scoped source records below for factual answers. Do not invent missing information. Use the read-only memory tool for relevant details and current sources; memory does not grant authority to act.',
    tr: 'Olgusal yanıtlar için aşağıdaki eksiksiz, kapsamı belirlenmiş kaynak kayıtlarını kullan. Eksik bilgiyi uydurma. İlgili ayrıntılar ve güncel kaynaklar için salt-okunur bellek aracını kullan; bellek işlem yapma yetkisi vermez.',
  },
  'bot.memory.context.absent': { en: 'No matching records in this memory scope.', tr: 'Bu bellek kapsamında eşleşen kayıt yok.' },
  'bot.memory.context.hold': { en: 'Memory context is unavailable: {reason}. Do not assume missing context is empty.', tr: 'Bellek bağlamı kullanılamıyor: {reason}. Erişilemeyen bağlamı boş kabul etme.' },
  'bot.memory.tool.invalid_request': { en: 'Invalid memory query or continuation reference.', tr: 'Bellek sorgusu veya devam referansı geçersiz.' },
  'bot.memory.tool.unavailable': { en: 'Memory read unavailable: {reason}', tr: 'Bellek okuması kullanılamıyor: {reason}' },
  'memory_read.invalid_limits': {
    en: 'memory_read must contain only positive integer maxEntries, maxCandidates, maxBytes and maxLines values; maxEntries cannot exceed maxCandidates.',
    tr: 'memory_read yalnızca pozitif tamsayı maxEntries, maxCandidates, maxBytes ve maxLines değerlerini içerebilir; maxEntries, maxCandidates değerini aşamaz.',
  },
  'memory_read.invalid_profiles': {
    en: 'memory_read_profiles must name supported memory consumers and contain valid whole-record read limits.',
    tr: 'memory_read_profiles desteklenen bellek tüketicilerini adlandırmalı ve geçerli tam kayıt okuma limitleri içermelidir.',
  },
  'memory_read.source': { en: 'Source', tr: 'Kaynak' },
  'memory_read.status': { en: 'Status', tr: 'Durum' },
  'memory_read.sprint': { en: 'Sprint', tr: 'Sprint' },
  'memory_read.updated_at': { en: 'Updated', tr: 'Güncellendi' },
  'memory_read.deferred': { en: 'Complete record available through its detail reference', tr: 'Eksiksiz kayıt ayrıntı referansı üzerinden erişilebilir' },
  'memory_read.detail': { en: 'Full detail', tr: 'Tam ayrıntı' },
  'memory_read.continuation': { en: 'Next page', tr: 'Sonraki sayfa' },
  'memory_read.cursor_help': { en: 'Continue the same scoped memory query using its next-page reference', tr: 'Sonraki sayfa referansıyla aynı kapsamdaki bellek sorgusunu sürdür' },
  'memory_read.detail_help': { en: 'Read the complete source record using its exact detail reference', tr: 'Kesin ayrıntı referansıyla eksiksiz kaynak kaydını oku' },
  'memory_read.hold': { en: 'Memory context unavailable: {reason}', tr: 'Bellek bağlamı kullanılamıyor: {reason}' },
  'memory_read.absent': { en: 'No matching memory records.', tr: 'Eşleşen bellek kaydı yok.' },
};
