export const MEMORY_EXPORT_MESSAGES: Record<string, Record<string, string>> = {
  'memory_export.summary_title': { en: 'Brain Summary (auto-generated)', tr: 'Beyin Özeti (otomatik oluşturuldu)' },
  'memory_export.decisions_title': { en: 'Architecture Decision Records (auto-generated)', tr: 'Mimari Karar Kayıtları (otomatik oluşturuldu)' },
  'memory_export.active_architecture_decisions': { en: 'Active Architecture Decisions', tr: 'Etkin Mimari Kararlar' },
  'memory_export.no_architecture_decisions': { en: 'No architecture decisions recorded.', tr: 'Kayıtlı mimari karar yok.' },
  'memory_export.recent_learnings': { en: 'Recent Learnings', tr: 'Son Öğrenimler' },
  'memory_export.legacy_epoch_learnings': { en: 'Legacy Epoch Learnings', tr: 'Eski Epoch Öğrenimleri' },
  'memory_export.unattributed_learnings': { en: 'Learnings Without Sprint Attribution', tr: 'Sprint Atfı Olmayan Öğrenimler' },
  'memory_export.no_learnings': { en: 'No learnings recorded.', tr: 'Kayıtlı öğrenim yok.' },
  'memory_export.sprint_learnings': { en: 'Sprint Learnings (auto-generated)', tr: 'Sprint Öğrenimleri (otomatik oluşturuldu)' },
  'memory_export.memory_details_title': { en: 'Complete Memory Source Records (auto-generated)', tr: 'Eksiksiz Bellek Kaynak Kayıtları (otomatik oluşturuldu)' },
  'memory_export.sprint_learning_heading': { en: 'Sprint {sprintId} Learnings', tr: '{sprintId} Sprint Öğrenimleri' },
  'memory_export.details': { en: 'Full details', tr: 'Tüm ayrıntılar' },
  'memory_export.full_details': { en: 'Complete source record', tr: 'Eksiksiz kaynak kaydı' },
  'memory_export.bounded_view_notice': { en: 'Complete records continue in {detailsFile}.', tr: 'Eksiksiz kayıtlar {detailsFile} içinde devam eder.' },
  'memory_export.memory_index': { en: 'Complete memory index', tr: 'Eksiksiz bellek dizini' },
  'memory_export.view_budget_floor_exceeded': { en: 'The complete record index exceeds the configured view target; no record IDs were omitted.', tr: 'Eksiksiz kayıt dizini yapılandırılmış görünüm hedefini aşıyor; hiçbir kayıt kimliği çıkarılmadı.' },
  'memory_export.id': { en: 'ID', tr: 'Kimlik' },
  'memory_export.title': { en: 'Title', tr: 'Başlık' },
  'memory_export.status': { en: 'Status', tr: 'Durum' },
  'memory_export.sprint_id': { en: 'Sprint ID', tr: 'Sprint Kimliği' },
  'memory_export.active_technical_debt': { en: 'Active Technical Debt', tr: 'Etkin Teknik Borç' },
  'memory_export.no_active_technical_debt': { en: 'No active technical debt.', tr: 'Etkin teknik borç yok.' },
  'memory_export.active_patterns': { en: 'Active Patterns', tr: 'Etkin Desenler' },
  'memory_export.no_active_patterns': { en: 'No active patterns.', tr: 'Etkin desen yok.' },
  'memory_export.technical_debt_title': { en: 'Technical Debt (auto-generated)', tr: 'Teknik Borç (otomatik oluşturuldu)' },
  'memory_export.resolved_technical_debt': { en: 'Resolved Technical Debt', tr: 'Çözülmüş Teknik Borç' },
  'memory_export.no_technical_debt': { en: 'No technical debt recorded.', tr: 'Kayıtlı teknik borç yok.' },
  'memory_export.priority': { en: 'Priority', tr: 'Öncelik' },
  'memory_export.total_entries_generated': { en: 'Total entries: {total} | Generated: {date}', tr: 'Toplam kayıt: {total} | Oluşturulma: {date}' },
  'memory_export.repeated_pattern': { en: '{title} (×{count} sprints)', tr: '{title} (×{count} sprint)' },
};
